[versions]
agp = "8.6.0"
appcompatVersion = "1.6.1"
coreKtxVersion = "1.4.1"
devMaterial = "1.6.6"
devRikkaRikkaxRecyclerviewRecyclerviewAdapter3 = "1.3.0"
devRikkaRikkaxWidgetBorderview = "1.1.0"
guava = "32.1.2-android"
cbor = "0.9"
htmlKtxVersion = "1.1.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
cbor = { module = "co.nstant.in:cbor", version.ref = "cbor" }

dev-html-ktx = { module = "dev.rikka.rikkax.html:html-ktx", version.ref = "htmlKtxVersion" }
dev-rikka-rikkax-material-material = { module = "dev.rikka.rikkax.material:material", version.ref = "devMaterial" }
dev-core-ktx = { module = "dev.rikka.rikkax.core:core-ktx", version.ref = "coreKtxVersion" }
dev-rikka-rikkax-widget-borderview2 = { module = "dev.rikka.rikkax.widget:borderview", version.ref = "devRikkaRikkaxWidgetBorderview" }
dev-rikka-rikkax-recyclerview-recyclerview-adapter5 = { module = "dev.rikka.rikkax.recyclerview:recyclerview-adapter", version.ref = "devRikkaRikkaxRecyclerviewRecyclerviewAdapter3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

